apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo
  namespace: demo
  labels:
    app: demo
    release: monitoring
spec:
  selector:
    matchLabels:
      app: demo
  endpoints:
    - interval: 15s
      port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - demo
