name: Build, Push Image & Update GitOps Manifests

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}    
  GITOPS_BRANCH: gitops
  DEPLOY_PATH: deploy/base/deployment.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine SHA tag
        id: vars
        run: |
          SHA_TAG="${GITHUB_SHA::7}"
          echo "sha_tag=$SHA_TAG" >> $GITHUB_OUTPUT

      - name: Build and push image (SHA only)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

    #   - name: Checkout GitOps branch
    #     uses: actions/checkout@v4
    #     with:
    #       ref: ${{ env.GITOPS_BRANCH }}

    #   - name: Update image tag in GitOps deployment
    #     run: |
    #       NEW_IMAGE="${REGISTRY}/${IMAGE_NAME}:${{ steps.vars.outputs.sha_tag }}"
    #       echo "Updating image in ${DEPLOY_PATH} to: $NEW_IMAGE"

    #       sed -i "s|image: .*|image: ${NEW_IMAGE}|g" "${DEPLOY_PATH}"

    #   - name: Commit and push changes
    #     run: |
    #       git config user.name "github-actions[bot]"
    #       git config user.email "github-actions[bot]@users.noreply.github.com"

    #       git add "${DEPLOY_PATH}"
    #       git commit -m "chore(gitops): update image to SHA ${{ steps.vars.outputs.sha_tag }}"
    #       git push origin ${{ env.GITOPS_BRANCH }}

    #   - name: Summary
    #     run: |
    #       echo "Image pushed: ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_tag }}"
    #       echo "GitOps manifest updated in branch: ${GITOPS_BRANCH}"
